name: Analytics Service CI

on:
  push:
    branches:
      - feature/ci-python

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: fiap-tech-challenge-devops/reusable-workflows/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.9"
      ecr-repository: "togglemaster/analytics-service"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}